from __future__ import annotations

import asyncio
import json
import os
import socket
import threading
import time
import uuid
from typing import Any, Callable

from service_club.storage.relational import RelationalBackend, RelationalConnection


def ensure_event_outbox_schema(connection: RelationalConnection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS event_outbox (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id TEXT NOT NULL UNIQUE,
            event_type TEXT NOT NULL,
            aggregate_type TEXT NOT NULL,
            aggregate_id TEXT NOT NULL,
            partition_key TEXT NOT NULL,
            payload_json TEXT NOT NULL,
            attempts INTEGER NOT NULL DEFAULT 0,
            claimed_by TEXT NOT NULL DEFAULT '',
            claim_until DOUBLE PRECISION,
            available_at DOUBLE PRECISION NOT NULL DEFAULT 0,
            published_at DOUBLE PRECISION,
            last_error TEXT NOT NULL DEFAULT '',
            created_at DOUBLE PRECISION NOT NULL
        )
        """
    )
    connection.execute(
        "ALTER TABLE event_outbox ADD COLUMN IF NOT EXISTS available_at DOUBLE PRECISION NOT NULL DEFAULT 0"
    )
    connection.execute(
        "CREATE INDEX IF NOT EXISTS idx_event_outbox_dispatch_v2 ON event_outbox(published_at, available_at, claim_until, id)"
    )


def append_outbox_event(
    connection: RelationalConnection,
    *,
    event_type: str,
    aggregate_type: str,
    aggregate_id: str,
    partition_key: str,
    payload: dict[str, Any],
) -> None:
    """Write an event in the caller's PostgreSQL transaction."""
    connection.execute(
        """
        INSERT INTO event_outbox(
            event_id, event_type, aggregate_type, aggregate_id,
            partition_key, payload_json, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(event_id) DO NOTHING
        """,
        (
            uuid.uuid4().hex,
            event_type[:120],
            aggregate_type[:80],
            aggregate_id[:160],
            partition_key[:240],
            json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
            time.time(),
        ),
    )


class KafkaOutboxDispatcher:
    """Lease PostgreSQL outbox rows and publish them to Kafka at least once."""

    def __init__(
        self,
        backend: RelationalBackend,
        *,
        projector: Callable[[str, dict[str, Any]], None] | None = None,
    ) -> None:
        self.backend = backend
        self.bootstrap_servers = os.getenv("YUKINO_KAFKA_BOOTSTRAP_SERVERS", "127.0.0.1:9093").strip()
        self.topic = os.getenv("YUKINO_KAFKA_TOPIC", "agi-yukino.events.v1").strip()
        self.instance_id = f"{socket.gethostname()}-{os.getpid()}-{uuid.uuid4().hex[:8]}"
        self._producer: Any | None = None
        self._thread: threading.Thread | None = None
        self._consumer_thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._last_error = ""
        self._published = 0
        self._dispatch_cycles = 0
        self._projector = projector
        self._listeners: set[tuple[asyncio.AbstractEventLoop, asyncio.Queue[str]]] = set()
        self._listeners_lock = threading.RLock()

    def start(self) -> None:
        if self._thread is not None and self._thread.is_alive():
            return
        self._producer = self._create_producer()
        self._stop.clear()
        self._thread = threading.Thread(target=self._run, name="yukino-kafka-outbox", daemon=True)
        self._thread.start()
        self._consumer_thread = threading.Thread(
            target=self._consume_notifications,
            name="yukino-kafka-notifier",
            daemon=True,
        )
        self._consumer_thread.start()

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=10)
        if self._consumer_thread is not None:
            self._consumer_thread.join(timeout=10)
        if self._producer is not None:
            self._producer.flush(10)
        self._thread = None
        self._consumer_thread = None

    def subscribe_local(
        self, loop: asyncio.AbstractEventLoop
    ) -> asyncio.Queue[str]:
        queue: asyncio.Queue[str] = asyncio.Queue(maxsize=256)
        with self._listeners_lock:
            self._listeners.add((loop, queue))
        return queue

    def unsubscribe_local(self, queue: asyncio.Queue[str]) -> None:
        with self._listeners_lock:
            self._listeners = {
                listener for listener in self._listeners if listener[1] is not queue
            }

    def dispatch_once(self, *, limit: int = 200) -> int:
        self._dispatch_cycles += 1
        if self._dispatch_cycles % 100 == 0:
            self._cleanup_published()
        producer = self._producer or self._create_producer()
        rows = self._claim(limit=limit)
        if not rows:
            producer.poll(0)
            return 0
        delivered: list[int] = []
        failures: dict[int, str] = {}
        for row in rows:
            row_id = int(row["id"])
            envelope = {
                "schema_version": 1,
                "event_id": str(row["event_id"]),
                "event_type": str(row["event_type"]),
                "aggregate_type": str(row["aggregate_type"]),
                "aggregate_id": str(row["aggregate_id"]),
                "occurred_at": float(row["created_at"]),
                "payload": json.loads(str(row["payload_json"])),
            }

            try:
                if self._projector is not None:
                    self._projector(str(row["event_type"]), envelope["payload"])
            except Exception as exc:
                failures[row_id] = f"projection {type(exc).__name__}: {str(exc)[:430]}"
                continue

            def on_delivery(error: Any, _message: Any, *, claimed_id: int = row_id) -> None:
                if error is None:
                    delivered.append(claimed_id)
                else:
                    failures[claimed_id] = str(error)[:500]

            try:
                producer.produce(
                    self.topic,
                    key=str(row["partition_key"]).encode("utf-8"),
                    value=json.dumps(envelope, ensure_ascii=False, separators=(",", ":")).encode("utf-8"),
                    headers=[("event_id", str(row["event_id"]))],
                    on_delivery=on_delivery,
                )
                producer.poll(0)
            except Exception as exc:
                failures[row_id] = f"{type(exc).__name__}: {str(exc)[:450]}"
        producer.flush(10)
        self._settle(delivered, failures)
        self._published += len(delivered)
        self._last_error = next(iter(failures.values()), "")
        return len(delivered)

    def status(self, *, probe: bool = False) -> dict[str, Any]:
        if probe:
            try:
                from confluent_kafka.admin import AdminClient

                AdminClient(
                    self._client_config(
                        client_id=f"agi-yukino-probe-{self.instance_id}"
                    )
                ).list_topics(timeout=5)
                self._last_error = ""
            except Exception as exc:
                self._last_error = f"{type(exc).__name__}: {str(exc)[:500]}"
        with self.backend.connect() as conn:
            row = conn.execute(
                "SELECT COUNT(*) AS pending FROM event_outbox WHERE published_at IS NULL"
            ).fetchone()
        notifier_running = bool(
            self._consumer_thread and self._consumer_thread.is_alive()
        )
        return {
            "ok": bool(
                not self._last_error
                and (self._thread is None or notifier_running)
            ),
            "backend": "kafka",
            "bootstrap_servers": self.bootstrap_servers,
            "topic": self.topic,
            "delivery": "transactional_outbox_at_least_once",
            "pending": int(row["pending"]) if row else 0,
            "published": self._published,
            "notifier_running": notifier_running,
            "last_error": self._last_error,
        }

    def _run(self) -> None:
        poll = _env_float("YUKINO_KAFKA_OUTBOX_POLL_SECONDS", 0.25, 0.05, 10.0)
        while not self._stop.is_set():
            try:
                count = self.dispatch_once()
                if not count:
                    self._stop.wait(poll)
            except Exception as exc:
                self._last_error = f"{type(exc).__name__}: {str(exc)[:500]}"
                self._stop.wait(min(5.0, poll * 4))

    def _consume_notifications(self) -> None:
        consumer = None
        try:
            from confluent_kafka import Consumer

            config = self._client_config(
                client_id=f"agi-yukino-notifier-{self.instance_id}"
            )
            config.update(
                {
                    "group.id": f"agi-yukino-notifier-{self.instance_id}",
                    "auto.offset.reset": "latest",
                    "enable.auto.commit": True,
                }
            )
            consumer = Consumer(config)
            consumer.subscribe([self.topic])
            while not self._stop.is_set():
                message = consumer.poll(1.0)
                if message is None or message.error():
                    continue
                try:
                    envelope = json.loads(message.value().decode("utf-8"))
                except (AttributeError, UnicodeDecodeError, json.JSONDecodeError):
                    continue
                if envelope.get("aggregate_type") == "agent_task":
                    self._notify_local(str(envelope.get("aggregate_id") or ""))
        except Exception as exc:
            self._last_error = f"notifier {type(exc).__name__}: {str(exc)[:450]}"
        finally:
            if consumer is not None:
                consumer.close()

    def _notify_local(self, task_id: str) -> None:
        if not task_id:
            return
        with self._listeners_lock:
            listeners = list(self._listeners)
        for loop, queue in listeners:
            if loop.is_closed():
                self.unsubscribe_local(queue)
                continue
            loop.call_soon_threadsafe(self._offer_notification, queue, task_id)

    @staticmethod
    def _offer_notification(queue: asyncio.Queue[str], task_id: str) -> None:
        if not queue.full():
            queue.put_nowait(task_id)

    def _claim(self, *, limit: int) -> list[dict[str, Any]]:
        now = time.time()
        lease_until = now + 30.0
        with self.backend.connect() as conn:
            rows = conn.execute(
                """
                WITH candidates AS (
                    SELECT id FROM event_outbox
                    WHERE published_at IS NULL
                      AND available_at <= ?
                      AND (claim_until IS NULL OR claim_until < ?)
                    ORDER BY id
                    FOR UPDATE SKIP LOCKED
                    LIMIT ?
                )
                UPDATE event_outbox AS outbox
                SET claimed_by = ?, claim_until = ?, attempts = attempts + 1
                FROM candidates
                WHERE outbox.id = candidates.id
                RETURNING outbox.*
                """,
                (now, now, max(1, min(limit, 1000)), self.instance_id, lease_until),
            ).fetchall()
        return [dict(row) for row in rows]

    def _settle(self, delivered: list[int], failures: dict[int, str]) -> None:
        with self.backend.connect() as conn:
            if delivered:
                placeholders = ",".join("?" for _ in delivered)
                conn.execute(
                    f"UPDATE event_outbox SET published_at = ?, claimed_by = '', claim_until = NULL, last_error = '' WHERE id IN ({placeholders}) AND claimed_by = ?",
                    [time.time(), *delivered, self.instance_id],
                )
            for row_id, error in failures.items():
                conn.execute(
                    "UPDATE event_outbox SET claimed_by = '', claim_until = NULL, available_at = ?, last_error = ? WHERE id = ? AND claimed_by = ?",
                    (time.time() + 2.0, error, row_id, self.instance_id),
                )

    def _create_producer(self) -> Any:
        if not self.bootstrap_servers or not self.topic:
            raise ValueError("Kafka bootstrap servers 和 topic 均不能为空。")
        try:
            from confluent_kafka import Producer
        except ImportError as exc:
            raise RuntimeError("Kafka 事件流需要安装 confluent-kafka。") from exc
        config = self._client_config(client_id=f"agi-yukino-{self.instance_id}")
        config.update(
            {
                "enable.idempotence": True,
                "acks": "all",
                "compression.type": "zstd",
                "linger.ms": 5,
                "delivery.timeout.ms": 30000,
            }
        )
        return Producer(config)

    def _cleanup_published(self) -> int:
        retention_days = _env_float(
            "YUKINO_KAFKA_OUTBOX_RETENTION_DAYS", 7.0, 1.0, 90.0
        )
        cutoff = time.time() - retention_days * 86400
        with self.backend.connect() as conn:
            cursor = conn.execute(
                """
                WITH expired AS (
                    SELECT id FROM event_outbox
                    WHERE published_at IS NOT NULL AND published_at < ?
                    ORDER BY id LIMIT 5000
                )
                DELETE FROM event_outbox AS outbox
                USING expired
                WHERE outbox.id = expired.id
                """,
                (cutoff,),
            )
        return int(cursor.rowcount or 0)

    def _client_config(self, *, client_id: str) -> dict[str, Any]:
        config: dict[str, Any] = {
            "bootstrap.servers": self.bootstrap_servers,
            "client.id": client_id,
            "security.protocol": os.getenv(
                "YUKINO_KAFKA_SECURITY_PROTOCOL", "PLAINTEXT"
            ).strip(),
        }
        username = os.getenv("YUKINO_KAFKA_SASL_USERNAME", "").strip()
        password = os.getenv("YUKINO_KAFKA_SASL_PASSWORD", "")
        if username:
            config.update(
                {
                    "sasl.mechanism": os.getenv(
                        "YUKINO_KAFKA_SASL_MECHANISM", "PLAIN"
                    ).strip(),
                    "sasl.username": username,
                    "sasl.password": password,
                }
            )
        ca_location = os.getenv("YUKINO_KAFKA_SSL_CA_LOCATION", "").strip()
        if ca_location:
            config["ssl.ca.location"] = ca_location
        return config


def _env_float(name: str, default: float, minimum: float, maximum: float) -> float:
    try:
        value = float(os.getenv(name, str(default)))
    except ValueError:
        value = default
    return max(minimum, min(value, maximum))
