from __future__ import annotations

import os
import re
import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from service_club.storage.sqlite import sqlite_connection


# 作用：表示已配置的关系数据库驱动或连接后端不可用。
# 参数：无。
class RelationalBackendUnavailable(RuntimeError):
    pass


# 作用：统一 SQLite 与 PostgreSQL 的占位符和建表语法差异。
# 参数：无。
class RelationalConnection:
    """Small DB-API compatibility surface used by domain repositories."""

    # 作用：包装原始 DB-API 连接并记录参数占位符风格。
    # 参数 raw：尚未规范化的原始配置、JSON 文本或底层连接对象。
    # 参数 placeholder：当前数据库驱动使用的 SQL 参数占位符。
    def __init__(self, raw: Any, *, placeholder: str) -> None:
        self.raw = raw
        self.placeholder = placeholder

    # 作用：转换通用 SQL 后执行单条语句。
    # 参数 statement：使用问号占位符编写的通用 SQL 语句。
    # 参数 parameters：与 SQL 语句占位符对应的参数或参数集合。
    def execute(self, statement: str, parameters: Any = ()) -> Any:
        sql = statement
        if self.placeholder != "?":
            sql = sql.replace(
                "INTEGER PRIMARY KEY AUTOINCREMENT",
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            )
            sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
            sql = sql.replace("?", self.placeholder)
        return self.raw.execute(sql, parameters)

    # 作用：转换通用 SQL 后批量执行参数集合。
    # 参数 statement：使用问号占位符编写的通用 SQL 语句。
    # 参数 parameters：与 SQL 语句占位符对应的参数或参数集合。
    def executemany(self, statement: str, parameters: Any) -> Any:
        sql = statement
        if self.placeholder != "?":
            sql = sql.replace(
                "INTEGER PRIMARY KEY AUTOINCREMENT",
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            )
            sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
            sql = sql.replace("?", self.placeholder)
        return self.raw.executemany(sql, parameters)


# 作用：约定领域仓储依赖的关系数据库最小能力接口。
# 参数：无。
@runtime_checkable
# 作用：定义“RelationalBackend”相关的数据结构、异常类型或服务组件。
# 字段：name：该对象中的结构化字段。、location：该对象中的结构化字段。、float_type：该对象中的结构化字段。、identity_type：该对象中的结构化字段。
class RelationalBackend(Protocol):
    name: str
    location: str
    float_type: str
    identity_type: str

    # 作用：声明创建事务型关系数据库连接的接口。
    # 参数 immediate：是否在事务开始时立即取得写入锁。
    def connect(self, *, immediate: bool = False) -> Any: ...

    # 作用：声明对业务作用域加事务锁的接口。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 scope：需要在事务内串行化的业务锁作用域。
    def lock_scope(
        self,
        connection: RelationalConnection,
        scope: str,
    ) -> None: ...

    # 作用：声明生成行锁查询后缀的接口。
    # 参数 skip_locked：查询行锁时是否跳过已被其他事务锁定的记录。
    def for_update(self, *, skip_locked: bool = False) -> str: ...

    # 作用：声明检查当前模式中数据表是否存在的接口。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    def table_exists(
        self,
        connection: RelationalConnection,
        table: str,
    ) -> bool: ...

    # 作用：声明在迁移后重置自增序列的接口。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    # 参数 column：要检查或重置的数据库列名。
    def reseed_identity(
        self,
        connection: RelationalConnection,
        table: str,
        column: str,
    ) -> None: ...


# 作用：实现零配置本地 SQLite 关系存储适配器。
# 参数：无。
class SQLiteRelationalBackend:
    name = "sqlite"
    float_type = "REAL"
    identity_type = "INTEGER PRIMARY KEY AUTOINCREMENT"

    # 作用：解析 SQLite 文件路径并公开后端位置。
    # 参数 path：目标文件、数据库或状态存储路径。
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path).resolve()
        self.location = str(self.path)

    # 作用：打开统一配置的 SQLite 事务并按需抢占写锁。
    # 参数 immediate：是否在事务开始时立即取得写入锁。
    @contextmanager
    # 作用：执行“connect”对应的内部处理步骤，完成输入转换、状态处理并返回约定结果。
    # 参数 immediate：调用方传入的immediate，用于本次处理。
    # 作用：执行“connect”对应的内部处理步骤，完成输入转换、状态处理并返回约定结果。
    # 参数 immediate：调用方传入的immediate，用于本次处理。
    def connect(self, *, immediate: bool = False) -> Iterator[RelationalConnection]:
        with sqlite_connection(self.path) as raw:
            raw.row_factory = sqlite3.Row
            if immediate:
                raw.execute("BEGIN IMMEDIATE")
            yield RelationalConnection(raw, placeholder="?")

    # 作用：保留锁作用域接口；SQLite 由事务级写锁统一串行化。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 scope：需要在事务内串行化的业务锁作用域。
    def lock_scope(
        self,
        connection: RelationalConnection,
        scope: str,
    ) -> None:
        del connection, scope

    # 作用：返回空后缀，因为 SQLite 不支持 SELECT FOR UPDATE。
    # 参数 skip_locked：查询行锁时是否跳过已被其他事务锁定的记录。
    def for_update(self, *, skip_locked: bool = False) -> str:
        del skip_locked
        return ""

    # 作用：通过 sqlite_master 检查数据表是否存在。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    def table_exists(
        self,
        connection: RelationalConnection,
        table: str,
    ) -> bool:
        row = connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
            (table,),
        ).fetchone()
        return row is not None

    # 作用：保留迁移接口；SQLite 的冲突忽略写入无需额外重置。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    # 参数 column：要检查或重置的数据库列名。
    def reseed_identity(
        self,
        connection: RelationalConnection,
        table: str,
        column: str,
    ) -> None:
        del connection, table, column


# 作用：实现支持行锁和顾问锁的 PostgreSQL 关系存储适配器。
# 参数：无。
class PostgresRelationalBackend:
    name = "postgresql"
    float_type = "DOUBLE PRECISION"
    identity_type = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

    # 作用：校验 DSN 并设置可观测的连接应用名。
    # 参数 dsn：连接 PostgreSQL 所需的 DSN。
    # 参数 application_name：写入 PostgreSQL 连接信息的应用标识。
    def __init__(self, dsn: str, *, application_name: str = "agi-yukino") -> None:
        if not dsn.startswith(("postgresql://", "postgres://")):
            raise ValueError("PostgreSQL DSN 必须使用 postgresql:// 或 postgres://。")
        self._dsn = dsn
        self.application_name = application_name[:63]
        self.location = "postgresql://configured"

    # 作用：懒加载 psycopg 并创建带超时和字典行的事务连接。
    # 参数 immediate：是否在事务开始时立即取得写入锁。
    @contextmanager
    def connect(self, *, immediate: bool = False) -> Iterator[RelationalConnection]:
        del immediate
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RelationalBackendUnavailable(
                "PostgreSQL 后端需要安装 agi-yukino[postgres]。"
            ) from exc
        timeout = _bounded_timeout()
        with psycopg.connect(
            self._dsn,
            autocommit=False,
            connect_timeout=timeout,
            application_name=self.application_name,
            row_factory=dict_row,
        ) as raw:
            yield RelationalConnection(raw, placeholder="%s")

    # 作用：用事务级顾问锁串行化同一业务作用域。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 scope：需要在事务内串行化的业务锁作用域。
    def lock_scope(
        self,
        connection: RelationalConnection,
        scope: str,
    ) -> None:
        connection.execute(
            "SELECT pg_advisory_xact_lock(hashtextextended(?, 0))",
            (scope,),
        )

    # 作用：生成普通或跳过已锁行的 FOR UPDATE 子句。
    # 参数 skip_locked：查询行锁时是否跳过已被其他事务锁定的记录。
    def for_update(self, *, skip_locked: bool = False) -> str:
        return " FOR UPDATE SKIP LOCKED" if skip_locked else " FOR UPDATE"

    # 作用：查询当前 PostgreSQL 模式判断数据表是否存在。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    def table_exists(
        self,
        connection: RelationalConnection,
        table: str,
    ) -> bool:
        row = connection.execute(
            """
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema() AND table_name = ?
            """,
            (table,),
        ).fetchone()
        return row is not None

    # 作用：校验标识符后把序列调整到现有最大主键之后。
    # 参数 connection：当前事务使用的关系数据库连接。
    # 参数 table：要查询、迁移或维护的数据表名称。
    # 参数 column：要检查或重置的数据库列名。
    def reseed_identity(
        self,
        connection: RelationalConnection,
        table: str,
        column: str,
    ) -> None:
        if not _IDENTIFIER.fullmatch(table) or not _IDENTIFIER.fullmatch(column):
            raise ValueError("数据库标识符无效。")
        connection.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence(?, ?),
                COALESCE(MAX({column}), 0) + 1,
                false
            )
            FROM {table}
            """,
            (table, column),
        )


_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


# 作用：读取并限制 PostgreSQL 建连超时时间。
# 参数：无。
def _bounded_timeout() -> int:
    try:
        value = int(os.getenv("YUKINO_POSTGRES_CONNECT_TIMEOUT_SECONDS", "5"))
    except ValueError:
        value = 5
    return max(1, min(value, 30))


# 作用：根据进程配置选择统一的 SQLite 或 PostgreSQL 事实存储。
# 参数 sqlite_path：未配置远端数据库时使用的 SQLite 文件路径。
# 参数 database_url：显式指定的关系数据库 URL；为空时读取环境配置。
def configured_relational_backend(
    sqlite_path: str | Path,
    *,
    database_url: str | None = None,
) -> RelationalBackend:
    """Resolve one fact-store backend for the whole process.

    PostgreSQL is opt-in so a desktop installation stays zero-configuration.
    A configured but invalid URL fails closed instead of silently splitting
    writes between PostgreSQL and SQLite.
    """
    url = (
        os.getenv("YUKINO_DATABASE_URL", "")
        if database_url is None
        else database_url
    ).strip()
    if not url:
        return SQLiteRelationalBackend(sqlite_path)
    if url.startswith(("postgresql://", "postgres://")):
        return PostgresRelationalBackend(url)
    raise ValueError(
        "YUKINO_DATABASE_URL 目前仅支持 postgresql://；"
        "本地 SQLite 模式请删除该配置。"
    )
